apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: wiki-js2
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
   db: postgres
