apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-js2
  labels:
    app: wiki
  namespace: wiki-js2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
      - name: wiki-js
        image: requarks/wiki:2
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
            name: http
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: postgres-config
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: postgres-config
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: postgres-config
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: postgres-config
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef:
              key: DB_TYPE
              name: postgres-config
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: DB_PASS
              name: postgres-secret
      restartPolicy: Always
        



